<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "newsletter_cr"
 *
 * Auto generated by Extension Builder 2017-02-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'newsletter from clever reach',
	'description' => 'newsletter from clever reach ',
	'category' => 'plugin',
	'author' => 'Bingquan Bao',
	'author_email' => 'bingquan.bao@diva-e.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);