<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tags_filter"
 *
 * Auto generated by Extension Builder 2017-02-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Tags Filter',
	'description' => 'show objects according to tags ',
	'category' => 'plugin',
	'author' => 'Bingquan Bao',
	'author_email' => 'bingquan.bao@diva-e.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'news'  => '5.0.0-5.3.2'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);